-- FilmTrack M2 Slice 1A: rating + diary data contract
--
-- IMPORTANT:
--   This is version-controlled migration source only.
--   Creating/merging this file MUST NOT be treated as authorization to apply it
--   to any production Supabase project. Production execution requires a separate
--   explicit approval after CI, Preview and read-only production preflight.
--
-- Product contracts:
--   * one current rating per canonical (user, title, title_type)
--   * rating uses an integer 1..10 scale (half-star precision at UI level)
--   * diary allows multiple rows for the same title so rewatches are derivable
--   * diary is private-by-default through owner-only RLS
--   * no raw email or other PII is persisted in either table

begin;

create table if not exists public.user_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title_id bigint not null,
  title_type text not null,
  rating_10 smallint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_ratings_title_type_check
    check (title_type in ('movie', 'tv')),
  constraint user_ratings_rating_10_check
    check (rating_10 between 1 and 10),
  constraint user_ratings_user_title_identity_key
    unique (user_id, title_id, title_type)
);

create table if not exists public.diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title_id bigint not null,
  title_type text not null,
  watched_on date not null default current_date,
  created_at timestamptz not null default now(),
  constraint diary_entries_title_type_check
    check (title_type in ('movie', 'tv'))
);

-- Access patterns: owner history, current rating and title/date diary traversal.
create index if not exists user_ratings_user_updated_at_idx
  on public.user_ratings (user_id, updated_at desc);

create index if not exists user_ratings_title_identity_idx
  on public.user_ratings (title_id, title_type);

create index if not exists diary_entries_user_watched_on_idx
  on public.diary_entries (user_id, watched_on desc, id desc);

create index if not exists diary_entries_user_title_watched_on_idx
  on public.diary_entries (user_id, title_id, title_type, watched_on desc, id desc);

alter table public.user_ratings enable row level security;
alter table public.diary_entries enable row level security;

-- Rebuild idempotently so migration source can be inspected/replayed safely in
-- controlled environments without silently widening access.
drop policy if exists "Users can view their own ratings" on public.user_ratings;
drop policy if exists "Users can insert their own ratings" on public.user_ratings;
drop policy if exists "Users can update their own ratings" on public.user_ratings;
drop policy if exists "Users can delete their own ratings" on public.user_ratings;

create policy "Users can view their own ratings"
  on public.user_ratings
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their own ratings"
  on public.user_ratings
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own ratings"
  on public.user_ratings
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own ratings"
  on public.user_ratings
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can view their own diary" on public.diary_entries;
drop policy if exists "Users can insert their own diary" on public.diary_entries;
drop policy if exists "Users can update their own diary" on public.diary_entries;
drop policy if exists "Users can delete their own diary" on public.diary_entries;

create policy "Users can view their own diary"
  on public.diary_entries
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their own diary"
  on public.diary_entries
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own diary"
  on public.diary_entries
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own diary"
  on public.diary_entries
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Least privilege: anon receives no table privilege; authenticated can only
-- operate through RLS-protected CRUD.
revoke all privileges on table public.user_ratings from anon, authenticated;
revoke all privileges on table public.diary_entries from anon, authenticated;

grant select, insert, update, delete
  on table public.user_ratings
  to authenticated;

grant select, insert, update, delete
  on table public.diary_entries
  to authenticated;

commit;
